<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'brand_id' => 1,
                'name' => 'Sofa Vải Cao Cấp',
                'slug' => 'sofa-vai-cao-cap',
                'sku' => 'SOF001',
                'detailed_description' => 'Sofa bọc vải cao cấp, phù hợp cho phòng khách hiện đại.',
                'image_url' => 'images/sofa-vai-cao-cap.jpg',
                'price' => 25000.00,
                'discount_price' => 22000.00,
                'discount_percentage' => 12.00,
                'stock' => 12,
                'weight' => 20.0,
                'ratings_avg' => 4.5,
                'ratings_count' => 120,
                'status' => 1,
                'is_featured' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 2,
                'name' => 'Giường Gỗ Sồi',
                'slug' => 'giuong-go-soi',
                'sku' => 'BED001',
                'detailed_description' => 'Giường gỗ sồi tự nhiên, thiết kế sang trọng.',
                'image_url' => 'images/giuong-go-soi.jpg',
                'price' => 35000.00,
                'discount_price' => 31500.00,
                'discount_percentage' => 10.00,
                'stock' => 5,
                'weight' => 40.0,
                'ratings_avg' => 4.8,
                'ratings_count' => 180,
                'status' => 1,
                'is_featured' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 3,
                'name' => 'Tủ Quần Áo Gỗ Xoan Đào',
                'slug' => 'tu-quan-ao-go-xoan-dao',
                'sku' => 'WARD001',
                'detailed_description' => 'Tủ quần áo gỗ xoan đào chắc chắn, rộng rãi.',
                'image_url' => 'images/tu-go-xoan-dao.jpg',
                'price' => 30000.00,
                'discount_price' => 28000.00,
                'discount_percentage' => 7.00,
                'stock' => 7,
                'weight' => 50.0,
                'ratings_avg' => 4.6,
                'ratings_count' => 90,
                'status' => 1,
                'is_featured' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 1,
                'name' => 'Bàn Trà Gỗ Óc Chó',
                'slug' => 'ban-tra-go-oc-cho',
                'sku' => 'TABLE001',
                'detailed_description' => 'Bàn trà làm từ gỗ óc chó cao cấp, hoàn hảo cho phòng khách.',
                'image_url' => 'images/ban-tra-oc-cho.jpg',
                'price' => 15000.00,
                'discount_price' => 13500.00,
                'discount_percentage' => 10.00,
                'stock' => 10,
                'weight' => 15.0,
                'ratings_avg' => 4.7,
                'ratings_count' => 65,
                'status' => 1,
                'is_featured' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 4,
                'name' => 'Sofa Da Thật Sang Trọng',
                'slug' => 'sofa-da-that-sang-trong',
                'sku' => 'SOF002',
                'detailed_description' => 'Sofa da thật cao cấp, mang đến không gian sang trọng.',
                'image_url' => 'images/sofa-da-that.jpg',
                'price' => 55000.00,
                'discount_price' => 50000.00,
                'discount_percentage' => 9.00,
                'stock' => 4,
                'weight' => 30.0,
                'ratings_avg' => 4.9,
                'ratings_count' => 150,
                'status' => 1,
                'is_featured' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 5,
                'name' => 'Bàn Trang Điểm Gỗ Sồi',
                'slug' => 'ban-trang-diem-go-soi',
                'sku' => 'DRES001',
                'detailed_description' => 'Bàn trang điểm gỗ sồi với gương lớn.',
                'image_url' => 'images/ban-trang-diem-go-soi.jpg',
                'price' => 18000.00,
                'discount_price' => 16200.00,
                'discount_percentage' => 10.00,
                'stock' => 6,
                'weight' => 18.0,
                'ratings_avg' => 4.4,
                'ratings_count' => 50,
                'status' => 1,
                'is_featured' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 1,
                'name' => 'Kệ Tivi Gỗ Sồi',
                'slug' => 'ke-tivi-go-soi',
                'sku' => 'TVS001',
                'detailed_description' => 'Kệ tivi gỗ sồi thiết kế hiện đại.',
                'image_url' => 'images/ke-tivi-go-soi.jpg',
                'price' => 20000.00,
                'discount_price' => 18000.00,
                'discount_percentage' => 10.00,
                'stock' => 5,
                'weight' => 20.0,
                'ratings_avg' => 4.3,
                'ratings_count' => 80,
                'status' => 1,
                'is_featured' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 3,
                'name' => 'Tủ Quần Áo 4 Cánh',
                'slug' => 'tu-quan-ao-4-canh',
                'sku' => 'WARD002',
                'detailed_description' => 'Tủ quần áo 4 cánh rộng rãi, chất liệu bền bỉ.',
                'image_url' => 'images/tu-4-canh.jpg',
                'price' => 42000.00,
                'discount_price' => 38000.00,
                'discount_percentage' => 9.5,
                'stock' => 5,
                'weight' => 55.0,
                'ratings_avg' => 4.8,
                'ratings_count' => 95,
                'status' => 1,
                'is_featured' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Thêm các sản phẩm khác
            [
                'brand_id' => 1,
                'name' => 'Bàn Làm Việc Gỗ Thông',
                'slug' => 'ban-lam-viec-go-thong',
                'sku' => 'WKS001',
                'detailed_description' => 'Bàn làm việc gỗ thông, thiết kế đơn giản nhưng hiện đại.',
                'image_url' => 'images/ban-lam-viec-go-thong.jpg',
                'price' => 25000.00,
                'discount_price' => 22500.00,
                'discount_percentage' => 10.00,
                'stock' => 8,
                'weight' => 25.0,
                'ratings_avg' => 4.5,
                'ratings_count' => 60,
                'status' => 1,
                'is_featured' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 2,
                'name' => 'Giường Ngủ Bằng Gỗ',
                'slug' => 'giuong-ngu-bang-go',
                'sku' => 'BED002',
                'detailed_description' => 'Giường ngủ bằng gỗ, chắc chắn và thoải mái.',
                'image_url' => 'images/giuong-ngu-bang-go.jpg',
                'price' => 34000.00,
                'discount_price' => 31000.00,
                'discount_percentage' => 9.00,
                'stock' => 6,
                'weight' => 40.0,
                'ratings_avg' => 4.7,
                'ratings_count' => 55,
                'status' => 1,
                'is_featured' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 4,
                'name' => 'Ghế Sofa Băng',
                'slug' => 'ghe-sofa-bang',
                'sku' => 'SOF003',
                'detailed_description' => 'Ghế sofa băng thoải mái cho không gian sống.',
                'image_url' => 'images/ghe-sofa-bang.jpg',
                'price' => 32000.00,
                'discount_price' => 29000.00,
                'discount_percentage' => 9.38,
                'stock' => 3,
                'weight' => 28.0,
                'ratings_avg' => 4.6,
                'ratings_count' => 30,
                'status' => 1,
                'is_featured' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'brand_id' => 5,
                'name' => 'Kệ Sách Gỗ Tự Nhiên',
                'slug' => 'ke-sach-go-tu-nhien',
                'sku' => 'BOOKS001',
                'detailed_description' => 'Kệ sách gỗ tự nhiên, thiết kế hiện đại và tinh tế.',
                'image_url' => 'images/ke-sach-go-tu-nhien.jpg',
                'price' => 22000.00,
                'discount_price' => 20000.00,
                'discount_percentage' => 9.09,
                'stock' => 10,
                'weight' => 22.0,
                'ratings_avg' => 4.5,
                'ratings_count' => 45,
                'status' => 1,
                'is_featured' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 3,
                'name' => 'Tủ Giày Gỗ Công Nghiệp',
                'slug' => 'tu-giay-go-cong-nghiep',
                'sku' => 'SHOE001',
                'detailed_description' => 'Tủ giày gỗ công nghiệp với thiết kế thông minh, tiết kiệm không gian.',
                'image_url' => 'images/tu-giay-go-cong-nghiep.jpg',
                'price' => 15000.00,
                'discount_price' => 14000.00,
                'discount_percentage' => 6.67,
                'stock' => 8,
                'weight' => 18.0,
                'ratings_avg' => 4.4,
                'ratings_count' => 30,
                'status' => 1,
                'is_featured' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 2,
                'name' => 'Ghế Xoay Văn Phòng',
                'slug' => 'ghe-xoay-van-phong',
                'sku' => 'CHAIR001',
                'detailed_description' => 'Ghế xoay văn phòng tiện lợi, điều chỉnh chiều cao và có tựa lưng êm ái.',
                'image_url' => 'images/ghe-xoay-van-phong.jpg',
                'price' => 12000.00,
                'discount_price' => 11000.00,
                'discount_percentage' => 8.33,
                'stock' => 15,
                'weight' => 10.0,
                'ratings_avg' => 4.2,
                'ratings_count' => 70,
                'status' => 1,
                'is_featured' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'brand_id' => 4,
                'name' => 'Bàn Ăn Gỗ Tự Nhiên 6 Ghế',
                'slug' => 'ban-an-go-tu-nhien-6-ghe',
                'sku' => 'DINING001',
                'detailed_description' => 'Bàn ăn gỗ tự nhiên với 6 ghế, phù hợp cho gia đình.',
                'image_url' => 'images/ban-an-go-tu-nhien-6-ghe.jpg',
                'price' => 50000.00,
                'discount_price' => 48000.00,
                'discount_percentage' => 4.00,
                'stock' => 2,
                'weight' => 80.0,
                'ratings_avg' => 4.7,
                'ratings_count' => 60,
                'status' => 1,
                'is_featured' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }
}
